### ISSUE TITLE
bug: if scenes have the same name, they get overwritten

### ISSUE THREAD

**Issue by lpabon** [aipresenter/aipresenter#59]
With a yaml:

```yaml
config:
  ai_config:
    text_ai_filename: hungry_dog.txt
    voice_ai_filename: hungry_dog.wav
    chatgpt_config:
      style: you are a playful storyteller
actors:
  - name: Max
    description: a hungry dog
    voice_type: unused
    age: adult
    gender: male
    accent: british
locations:
  - name: Kitchen
    type: interior
    lighting: Bright
scenes:
  - location: Kitchen
    characters:
      - Max
    plot: Max enters the kitchen and sees his empty bowl.
  - location: Kitchen
    characters:
      - Max
    plot: Max starts barking at his bowl to get attention.
  - location: Kitchen
    characters:
      - Max
    plot: Max jumps around with excitement, still barking for food.
  - location: Kitchen
    characters:
      - Max
    plot: Max's owner finally fills his bowl, and Max happily munches on his food.
```

Only the last `Kitchen` scene is used because it is the single KEY used. We may have to rethink how we traverse through the scenes, instead probably use it as an array, not as a dictionary.
